# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s0z97EYmNrh3EYX6zJoBC62dmh7W8A-o
"""

import pandas as pd
import pymongo
def get_responce()
  MONGODB_URI = 'mongodb+srv://mrdanhik:0321@loser.2mlzec4.mongodb.net/alice?retryWrites=true&w=majority'
  client = pymongo.MongoClient(MONGODB_URI)  # тут должен быть ваш адрес mongo
  db = client.get_default_database()
  docs = pd.DataFrame(db.get_collection('logs').find())
  str = docs.utterance[-1:].iloc[0]
  str
return str